# Gnuplot script file automatically generated by Plot2D.java
# Plotting data in files ??
set term png
set xlabel "temperature"
set ylabel "dT/dt"
set output "./output/DAO_tempetatureVSderivative_delta4.0.png"
plot "./output/DAO_tempetatureVSderivative_delta4.0_derivVStemp" title "derivVStemp" with linespoints 