# Gnuplot script file automatically generated by Plot2D.java
# Plotting data in files ??
set term png
set xlabel "time"
set ylabel "temperature"
set output "./output/DAO_timeVStemperature_delta2.0.png"
plot "./output/DAO_timeVStemperature_delta2.0_temperature" title "temperature" with linespoints 